### ISSUE TITLE
class with list attribute are not hashable

### ISSUE THREAD

**Issue by hdeflaugergues** [JGiard/AutoValue#2]
```python
@autovalue
class Foo:
    def __init__(self, x):
        self.x = x

Foo([‘foobar']).__hash__()
Traceback (most recent call last):
  File "/Users/hugues.deflaugergues/Code/fluid/fluid-python-api/lib/python3.4/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-79-924720a17848>", line 1, in <module>
    Foo(['foobar']).__hash__()
  File "/Users/hugues.deflaugergues/Code/fluid/fluid-python-api/lib/python3.4/site-packages/autovalue/__init__.py", line 37, in cls_hash
    return hash(tuple(values))
TypeError: unhashable type: 'list'
 [['foobar']]
```

**Comment by JGiard** [comment]
this should already be solved by https://github.com/JGiard/AutoValue/commit/8ee10f7d862af6b176236e0cee1a63f03b7686d0
