### ISSUE TITLE
class that with __init__() parameter not used as attribute are not printable

### ISSUE THREAD

**Issue by hdeflaugergues** [JGiard/AutoValue#3]
```python
@autovalue
 class Foo:
     def __init__(self, x):
         pass

print(Foo(1))
 Traceback (most recent call last):
   File "lib/python3.4/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
     exec(code_obj, self.user_global_ns, self.user_ns)
   File "<ipython-input-89-021bb0045116>", line 1, in <module>
     print(Foo(1))
   File "lib/python3.4/site-packages/autovalue/__init__.py", line 40, in tostring
     attr_format = ['{}={}'.format(name, str(getattr(self, name))) for name in attributes]
   File "lib/python3.4/site-packages/autovalue/__init__.py", line 40, in <listcomp>
     attr_format = ['{}={}'.format(name, str(getattr(self, name))) for name in attributes]
 AttributeError: 'Foo' object has no attribute 'x'
```

**Comment by JGiard** [comment]
This is working as intended, autovalue uses the object constructor signature to discover the structure of your class
